CREATE TABLE IF NOT EXISTS movie(
    id NUMBER(3) PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(40) NOT NULL,
    rating NUMBER(3,1) NOT NULL,
    genre_id NUMBER(3)
);

CREATE TABLE IF NOT EXISTS genre(
    genre_id NUMBER(3) PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(40) NOT NULL
);